name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Formatted?
        run: |
          gofmt -l .
          test -z "`gofmt -l .`"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Benchmark
        run: go test -bench . ./...

      - name: Lint (staticcheck)
        uses: dominikh/staticcheck-action@v1
        with:
          install-go: false
          version: "2023.1.6"
